# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "d134dcc22cebb9379b06b323f8e63d28"
name = "Product Specification"
handle = "product-specification"
application_url = "https://angry-finite-visits-functionality.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_markets,write_content,write_markets,write_products"

[auth]
redirect_urls = [
  "https://angry-finite-visits-functionality.trycloudflare.com/auth/callback",
  "https://angry-finite-visits-functionality.trycloudflare.com/auth/shopify/callback",
  "https://angry-finite-visits-functionality.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
